### ISSUE TITLE
[Bug]: RedBot

### ISSUE THREAD

**Issue by Gizmo0320** [pelican-eggs/chatbots#10]
### Panel Version

1.0.0-beta7

### Wings Version

1.0.0-beta3

### Service

discord/redbot

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and be able to use it

### Actual Behavior

The following error occurs during startup
/entrypoint.sh: eval: line 13: syntax error near unexpected token `newline'
/entrypoint.sh: eval: line 13: `PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token "DISCORDTOKEN" --prefix >'

### Steps To Reproduce

Install the server, config Discord Token, prefix, and owner. Try and start the server

### Install logs

https://ptero.co/wakaqehemu

**Comment by QuintenQVD0** [comment]
there part of the install logs missing please run `tail -n 5000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99`

**Comment by QuintenQVD0** [comment]
I just tried this and it works just fine for me, please come to the discord to resolve this.
