### ISSUE TITLE
[Egg Request]: Sentinel Tickets Discord Bot

### ISSUE THREAD

**Issue by HerrSammyDE** [pelican-eggs/chatbots#6]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/ralphkb/sentinel-tickets

### Links for the download

https://github.com/ralphkb/sentinel-tickets/releases

### Links for the install docs

https://sentinel-tickets-docs.pages.dev/setup/installation/

**Comment by QuintenQVD0** [comment]
This seems like something so simple the generic nodejs can run this?

**Comment by HerrSammyDE** [comment]
I thought about that too, but didn't try it out

**Comment by QuintenQVD0** [comment]
> I thought about that too, but didn't try it out

the generic egg will run it, please try that.

**Comment by QuintenQVD0** [comment]
The generic nodejs egg can run this with the main file just set to index.js
